export const conversationConstants = {
  SET_CONVERSATION: "SET_CONVERSATION",
  ADD_CONVERSATION: "ADD_CONVERSATION",
  UPDATE_CONVERSATION: "UPDATE_CONVERSATION",
  DELETE_CONVERSATION: "DELETE_CONVERSATION",
  UPDATE_LAST_MESSAGE: "UPDATE_LAST_MESSAGE",

  SELECT_CONVERSATION: "SELECT_CONVERSATION",

  //socket
  CONVERSATION_CHANGE: "CONVERSATION_CHANGE",
  LAST_MESSAGE_UPDATE: "LAST_MESSAGE_UPDATE",
};
