export const messageConstants = {
  SET_MESSAGE: "SET_MESSAGE",
  ADD_MESSAGE: "ADD_MESSAGE",
  UPDATE_MESSAGE_WITH_CLIENTID: "UPDATE_MESSAGE_WITH_CLIENTID",
  UPDATE_MESSAGE_WITH_ID: "UPDATE_MESSAGE_WITH_ID",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  LOAD_MORE: "LOAD_MORE",
  PROGRESS_UPLOAD: "UPLOAD_PROGRESS",

  //socket event
  RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
  NEW_MESSAGE_RECEIVED: "NEW_MESSAGE_RECEIVED",
  SEND_MESSAGE: "SEND_MESSAGE",
  MESSAGE_SENT_RECEIVED: "MESSAGE_SENT_RECEIVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  TYPING_SEND: "TYPING_SEND",
  TYPING_REGISTER: "TYPING_REGISTER",
  TYPING_RECEIVE: "TYPING_RECEIVE",
};
