export const userConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  LOGOUT_REQUEST: "USERS_LOGOUT_REQUEST",
  LOGOUT_SUCESS: "USERS_LOGOUT_SUCESS",
  LOGOUT_FAIL: "USERS_LOGOUT_FAL",

  DISPLAY_USER: "DISPLAY_USER",

  NEW_KEY: "NEW_KEY",
  CREATE_NEW_KEY: "CREATE_NEW_KEY",
};
